### ISSUE TITLE
Tests failing with MoarVM hash changes

### ISSUE THREAD

**Issue by samcv** [pierre-vigier/Perl6-Data-MessagePack#13]
With the recent MoarVM changes the hashes don't always return in a constant order (even without these changes it means that the tests probably wouldn't pass on perl6 running other VM backends).

Failures are in t/107-pack-hash.t, in which I get up to 2 failing tests (it can fail less if for that particular run of MoarVM it just so happens to return the previous order that the test expected).

**Comment by AlexDaniel** [comment]
https://cry.nu/perl6/secure-hashing-for-moarvm/

**Comment by pierre-vigier** [comment]
Fixed now, thanks for the notice. Instead of checking the blob byte by byte, i pack, unpack and check the result against the original hash
